server:
  port: 8761

spring:
  application:
    #注册名称
    name: eureka-server

eureka:
  instance:
    hostname: 127.0.0.1

  client:
    #是否获取eureka服务器的注册信息，默认为true
    fetch-registry: false
    #是否注册到eureka服务器，默认为true
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/